export { type CapturedPhoto, type CapturePhotoOptions, pickPhoto, requestCameraPermissions, takePhoto } from './camera'
export { createCredentialStorage, type CredentialStorage } from './credential-storage'
export { deepLinkToPath } from './deep-link'
export { type DeviceSummary, getDeviceSummary } from './device'
export { type FeedbackType, type ImpactStrength, impact, notification } from './haptics'
export { createKeyValueStorage, type KeyValueStorage } from './key-value-storage'
export { type ConnectionType, readOnlineHint } from './network'
export { getPlatform, isAndroid, isIos, isNativePlatform, isPluginAvailable, type NativePlatform } from './platform'
export { hideSplashScreen } from './splash-screen'
export { setStatusBarAppearance, type StatusBarAppearance } from './status-bar'
export { type SharePayload, share } from './share'
